//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWebNangCao.View.BTL.view.client
{


    public partial class clientProductManager
    {

        /// <summary>
        /// ProductAdd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LapTrinhWebNangCao.View.BTL.userControl.AddProduct ProductAdd;

        /// <summary>
        /// Edit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LapTrinhWebNangCao.View.BTL.userControl.EditProduct Edit;

        /// <summary>
        /// Approve control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LapTrinhWebNangCao.View.BTL.userControl.ApproveProduct Approve;

        /// <summary>
        /// Disapprove control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LapTrinhWebNangCao.View.BTL.userControl.DisapproveProduct Disapprove;
    }
}
